### ISSUE TITLE
Question about de novo prediction of own datasets

### ISSUE THREAD

**Issue by JannikSchneider12** [instadeepai/InstaNovo#26]
Hello,

I wanted to try the model on my mgf files and I converted them with the provided script. The resulting .ipc file looks as follows:

![image](https://github.com/instadeepai/InstaNovo/assets/72038436/9e141f4a-2b2d-4e12-8049-348136b70242)

Since I don't have any peptide sequences and want to predict new ones.

However when I am trying to run the model with this command:

!python -m instanovo.transformer.predict /content/consensus_spectra.ipc /content/checkpoints/instanovo_yeast.pt --denovo --output_path /content/

I am getting this error:

INFO:root:Initializing inference.
INFO:root:Loading data from /content/consensus_spectra.ipc
INFO:root:Data loaded, evaluating 100.0%, 10931 samples in total.
INFO:root:Knapsack path missing or not specified, generating...
INFO:root:Scaling masses.
INFO:root:Initializing chart.
INFO:root:Performing search.
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'exceptions.ColumnNotFoundError'>: import of module 'exceptions' failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)

Is this because of the missing peptide sequence? And if so, how can I use the model to predict unidentified spectra?

Thanks for your time and help

**Comment by rcatzel** [comment]
Hi @JannikSchneider12,

Apologies for the very delayed response.

I see you used the ‘denovo’ flag - this should allow for predictions on unlabelled datasets to be made. We have recently released [InstaNovo 1.0.0](https://github.com/instadeepai/InstaNovo/releases/tag/1.0.0), along with an improved model checkpoint. There have been a number of changes made to our code base and I would expect this error to be resolved. Please let us know if you have any further questions.
